version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bg_remover_backend
    ports:
      - "8001:8001"
    volumes:
      # Mount src for potential code changes if using --reload later
      - ./src:/app/src 
      # Mount input/output directories
      - ./input:/app/input
      - ./output:/app/output
      # Mount the .env file
      - ./.env:/app/.env 
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bg_remover_frontend
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for development changes 
      # NOTE: Changes outside of src/ and public/ might require rebuild
      - ./frontend:/app
      # Use anonymous volumes for node_modules and .next to prevent host overriding
      - /app/node_modules 
      - /app/.next
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8001
      WATCHPACK_POLLING: "true" # Helps with file watching in Docker
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 