version: '3'

services:
  app:
    image: your_image_name
    environment:
      USE_LOCALSTACK: 'false'
    ports:
      - '3000:3000'
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,sns,sqs
      - DEFAULT_REGION=us-east-1
